### ISSUE TITLE
rule "not_in" error if the list is empty

### ISSUE THREAD

**Issue by erwinstone** [jadKhoury1/simple-body-validator#17]
Hello, thanks for this great validation library.
I have a problem with the "not_in" rule

For example
```javascript
username: `required|not_in:${existUsername}`
```
which is where the variable "existUsername" comes from the database

if the initial database is empty, then the variable will be empty and validation failed with error message
```bash
TypeError: Cannot read properties of undefined (reading 'split')
     at Object.parseParameters (/home/projects/node-dm87py/node_modules/simple-body-validator/lib/validators/validationRuleParser.js:122:26)
```

in this case, the "not_in" rule should pass if the list is empty

**Comment by jadKhoury1** [comment]
Hello, Thank you for raising the issue 

The **not_in** rule can only take a **string** as a valid data type, so **undefined** will fail in that case.

I suggest doing the following:

`const { make, ruleNotIn, Password } = require('simple-body-validator');

// let's say you have the following rules
let rules = {
  username: ['required'],
  password: ['required', Password.default()]
};

if (username) {
  rules.username.push(ruleNotIn([username]));
}

validator.setRules(rules);
`
I used **ruleNotIn** rule for simplicity, in order not to concatenate the rule in a string

**Comment by erwinstone** [comment]
Hello, Thank you for the advice

Since this library is inspired by laravel's validation mechanism, i think for this case it's best to follow what laravel does by passing it if the value is empty. But it's ok, I will follow your suggestion
