### ISSUE TITLE
Instant feedback missing

### ISSUE THREAD

**Issue by Ajax30** [jadKhoury1/simple-body-validator#29]
There should be _instant feedback_ on the forms, similar to the way validation works in Angular forms. There is detailed description of the problem in **[THIS](https://stackoverflow.com/q/77143524/4512005)** Stackoverflow question.

**Comment by jadKhoury1** [comment]
Hello @Ajax30, you can achieve instant feedback with **simple-body-validator**. You just need to add those two lines of code to the **handleChange** function:

```
    validator.validate(name, value);
    setErrors(validator.errors());
```
So your function will look like the following.

```
  const handleChange = (event) => {
    const { name, value } = event.target;
    setFormData((prevFormData) => ({ ...prevFormData, [name]: value }));

    validator.validate(name, value);
    setErrors(validator.errors());
  };
```

You can see the example in the [documentation](https://www.simple-body-validator.com/react/validation-quickstart#form-instant-validation-example)
