### ISSUE TITLE
Password confirmation

### ISSUE THREAD

**Issue by Ajax30** [jadKhoury1/simple-body-validator#30]
Password confirmation does not seem to work as written in the docs. There is an example **[here](https://stackoverflow.com/q/77166859/4512005)**.

**Comment by jadKhoury1** [comment]
Hello @Ajax30 thank you for posting the issue. As mentioned in the answer of stackoverflow. You need to add the **confirmed** rule to the **password**. The **confirmed** rule will inform the library to validate the **password** against the **password_confirmation** field.
