### ISSUE TITLE
Validate image formates

### ISSUE THREAD

**Issue by Ajax30** [jadKhoury1/simple-body-validator#31]
If I have in input of type file, how do I restrict the accepted formats to JPG and PNG? I have tryed `avatar: ["mimes:jpg,png"]`, but it fails.

**Comment by jadKhoury1** [comment]
Currently, the library does not support **mimes** validation. However, you might be able to achieve it by creating a custom validation [rule](https://www.simple-body-validator.com/custom-validation-rules)

**Comment by Ajax30** [comment]
> Currently, the library does not support **mimes** validation. However, you might be able to achieve it by creating a custom validation [rule](https://www.simple-body-validator.com/custom-validation-rules)

I did this, but it does not show any message: :(

```
register('mimes', function (value) {
  return value.match(/\.(jpg|jpeg|png)$/);
});
```

**Comment by jadKhoury1** [comment]
Hello @Ajax30, you have two ways to register the rule by either doing what you already did:

```
register('mimes', function (value) {
  return value.match(/\.(jpg|jpeg|png)$/);
});
```

or by using the [custom class ](https://www.simple-body-validator.com/custom-validation-rules#create-custom-rule-using-a-class).

1- When using the **register** method you must follow the **Translating Error Messages** [documentation](https://www.simple-body-validator.com/error-messages/translating-error-messages) to add your message.
You can also follow this [example](https://www.simple-body-validator.com/react/translation) to achieve this in React.

2- This is an example of how to achieve it with the custom class, let's say we create a class called **Mimes**:

```
    const { Rule } = require('simple-body-validator');

    class Mimes extends Rule {
        passes(value) {
          return value.match(/\.(jpg|jpeg|png)$/);
        }

        getMessage() {
            return 'The :attribute field must be a file of type jpg, jpej, or png.';
        }
    };
```

You can use the class as follows:

```
  const rules = [ 
     image: [ 'required', new Mimes ]
  ];
```

**Note**: You can still use the translations in your class if you wish by using the following function in the **getMessage** method:

```
    getMessage() {
        return this.trans('mimes');
    }
```
